// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TMS.Data.DatabaseContext;

#nullable disable

namespace TMS.Data.Migrations
{
    [DbContext(typeof(TMSDbContext))]
    partial class TMSDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TMS.Data.DatabaseModels.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimezoneId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CityId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CityId = 1,
                            CityName = "Vancouver",
                            TimezoneId = "Pacific Standard Time"
                        },
                        new
                        {
                            CityId = 2,
                            CityName = "Victoria",
                            TimezoneId = "Pacific Standard Time"
                        },
                        new
                        {
                            CityId = 3,
                            CityName = "Kelowna",
                            TimezoneId = "Pacific Standard Time"
                        },
                        new
                        {
                            CityId = 4,
                            CityName = "Kamloops",
                            TimezoneId = "Pacific Standard Time"
                        },
                        new
                        {
                            CityId = 5,
                            CityName = "Prince George",
                            TimezoneId = "Pacific Standard Time"
                        },
                        new
                        {
                            CityId = 6,
                            CityName = "Calgary",
                            TimezoneId = "Mountain Standard Time"
                        },
                        new
                        {
                            CityId = 7,
                            CityName = "Edmonton",
                            TimezoneId = "Mountain Standard Time"
                        },
                        new
                        {
                            CityId = 8,
                            CityName = "Lethbridge",
                            TimezoneId = "Mountain Standard Time"
                        },
                        new
                        {
                            CityId = 9,
                            CityName = "Red Deer",
                            TimezoneId = "Mountain Standard Time"
                        },
                        new
                        {
                            CityId = 10,
                            CityName = "Fort McMurray",
                            TimezoneId = "Mountain Standard Time"
                        },
                        new
                        {
                            CityId = 11,
                            CityName = "Regina",
                            TimezoneId = "Canada Central Standard Time"
                        },
                        new
                        {
                            CityId = 12,
                            CityName = "Saskatoon",
                            TimezoneId = "Canada Central Standard Time"
                        },
                        new
                        {
                            CityId = 13,
                            CityName = "Moose Jaw",
                            TimezoneId = "Canada Central Standard Time"
                        },
                        new
                        {
                            CityId = 14,
                            CityName = "Brandon",
                            TimezoneId = "Central Standard Time"
                        },
                        new
                        {
                            CityId = 15,
                            CityName = "Winnipeg",
                            TimezoneId = "Central Standard Time"
                        },
                        new
                        {
                            CityId = 16,
                            CityName = "Thunder Bay",
                            TimezoneId = "Eastern Standard Time"
                        },
                        new
                        {
                            CityId = 17,
                            CityName = "Sault Ste. Marie",
                            TimezoneId = "Eastern Standard Time"
                        },
                        new
                        {
                            CityId = 18,
                            CityName = "Sudbury",
                            TimezoneId = "Eastern Standard Time"
                        },
                        new
                        {
                            CityId = 19,
                            CityName = "North Bay",
                            TimezoneId = "Eastern Standard Time"
                        },
                        new
                        {
                            CityId = 20,
                            CityName = "Barrie",
                            TimezoneId = "Eastern Standard Time"
                        },
                        new
                        {
                            CityId = 21,
                            CityName = "Toronto",
                            TimezoneId = "Eastern Standard Time"
                        },
                        new
                        {
                            CityId = 22,
                            CityName = "Mississauga",
                            TimezoneId = "Eastern Standard Time"
                        },
                        new
                        {
                            CityId = 23,
                            CityName = "Hamilton",
                            TimezoneId = "Eastern Standard Time"
                        },
                        new
                        {
                            CityId = 24,
                            CityName = "London",
                            TimezoneId = "Eastern Standard Time"
                        },
                        new
                        {
                            CityId = 25,
                            CityName = "Kitchener",
                            TimezoneId = "Eastern Standard Time"
                        },
                        new
                        {
                            CityId = 26,
                            CityName = "Windsor",
                            TimezoneId = "Eastern Standard Time"
                        },
                        new
                        {
                            CityId = 27,
                            CityName = "St. Catharines",
                            TimezoneId = "Eastern Standard Time"
                        },
                        new
                        {
                            CityId = 28,
                            CityName = "Oshawa",
                            TimezoneId = "Eastern Standard Time"
                        },
                        new
                        {
                            CityId = 29,
                            CityName = "Kingston",
                            TimezoneId = "Eastern Standard Time"
                        },
                        new
                        {
                            CityId = 30,
                            CityName = "Ottawa",
                            TimezoneId = "Eastern Standard Time"
                        },
                        new
                        {
                            CityId = 31,
                            CityName = "Gatineau",
                            TimezoneId = "Eastern Standard Time"
                        },
                        new
                        {
                            CityId = 32,
                            CityName = "Montreal",
                            TimezoneId = "Eastern Standard Time"
                        },
                        new
                        {
                            CityId = 33,
                            CityName = "Quebec City",
                            TimezoneId = "Eastern Standard Time"
                        },
                        new
                        {
                            CityId = 34,
                            CityName = "Sherbrooke",
                            TimezoneId = "Eastern Standard Time"
                        },
                        new
                        {
                            CityId = 35,
                            CityName = "Trois-Rivières",
                            TimezoneId = "Eastern Standard Time"
                        },
                        new
                        {
                            CityId = 36,
                            CityName = "Saguenay",
                            TimezoneId = "Eastern Standard Time"
                        },
                        new
                        {
                            CityId = 37,
                            CityName = "Rimouski",
                            TimezoneId = "Eastern Standard Time"
                        },
                        new
                        {
                            CityId = 38,
                            CityName = "Edmundston",
                            TimezoneId = "Atlantic Standard Time"
                        },
                        new
                        {
                            CityId = 39,
                            CityName = "Fredericton",
                            TimezoneId = "Atlantic Standard Time"
                        },
                        new
                        {
                            CityId = 40,
                            CityName = "Moncton",
                            TimezoneId = "Atlantic Standard Time"
                        },
                        new
                        {
                            CityId = 41,
                            CityName = "Saint John",
                            TimezoneId = "Atlantic Standard Time"
                        },
                        new
                        {
                            CityId = 42,
                            CityName = "Bathurst",
                            TimezoneId = "Atlantic Standard Time"
                        },
                        new
                        {
                            CityId = 43,
                            CityName = "Charlottetown",
                            TimezoneId = "Atlantic Standard Time"
                        },
                        new
                        {
                            CityId = 44,
                            CityName = "Summerside",
                            TimezoneId = "Atlantic Standard Time"
                        },
                        new
                        {
                            CityId = 45,
                            CityName = "Sydney",
                            TimezoneId = "Atlantic Standard Time"
                        },
                        new
                        {
                            CityId = 46,
                            CityName = "Truro",
                            TimezoneId = "Atlantic Standard Time"
                        },
                        new
                        {
                            CityId = 47,
                            CityName = "New Glasgow",
                            TimezoneId = "Atlantic Standard Time"
                        },
                        new
                        {
                            CityId = 48,
                            CityName = "Dartmouth",
                            TimezoneId = "Atlantic Standard Time"
                        },
                        new
                        {
                            CityId = 49,
                            CityName = "Halifax",
                            TimezoneId = "Atlantic Standard Time"
                        });
                });

            modelBuilder.Entity("TMS.Data.DatabaseModels.RailCarEventRecord", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("EquipmentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EventTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.HasKey("EventId");

                    b.HasIndex("TripId");

                    b.ToTable("RailCarEventRecord");
                });

            modelBuilder.Entity("TMS.Data.DatabaseModels.Trips", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TripId"));

                    b.Property<string>("DestinationCityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EquipmentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginCityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalHours")
                        .HasColumnType("int");

                    b.HasKey("TripId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("TMS.Data.DatabaseModels.RailCarEventRecord", b =>
                {
                    b.HasOne("TMS.Data.DatabaseModels.Trips", "Trip")
                        .WithMany("RailCarEventRecords")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TMS.Data.DatabaseModels.Trips", b =>
                {
                    b.Navigation("RailCarEventRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
